version: '3.8'

services:
  backend:
    build: ./apps/backend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  
  frontend:
    build: ./apps/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
