version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: empire
      POSTGRES_USER: empire
      POSTGRES_PASSWORD: empire
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./apps/backend
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

  worker:
    build: ./apps/backend
    command: ["npm", "run", "worker"]
    env_file: .env
    depends_on:
      - api
      - db
      - redis

  web:
    build: ./apps/frontend
    ports:
      - "5173:5173"

volumes:
  dbdata: {}
